"""Core authentication orchestration service.

Wires together security primitives, email stubs, and an in-memory store
for pending signups.  Will be backed by a database in a later iteration.
"""

from __future__ import annotations

from datetime import datetime, timezone

from fastapi import HTTPException

from api.schemas.auth import (
    EmailVerifyResponse,
    ForgotPasswordResponse,
    LoginResponse,
    OrgStatus,
    PendingSignup,
    RecoveryCodeResponse,
    SignupStartRequest,
    SignupStartResponse,
    TwoFAChallengeResponse,
    TwoFASetupConfirmResponse,
    TwoFASetupStartResponse,
    UserStatus,
)
from api.services.email import send_password_reset_email, send_verification_email
from api.services.security import (
    create_access_token,
    create_refresh_token,
    decode_token,
    generate_recovery_codes,
    generate_totp_secret,
    generate_verification_token,
    get_totp_provisioning_uri,
    get_totp_qr_svg_base64,
    hash_password,
    verify_password,
    verify_totp_code,
    verify_verification_token,
)

# ---------------------------------------------------------------------------
# In-memory store
# ---------------------------------------------------------------------------

_pending_signups: dict[str, PendingSignup] = {}
_used_tokens: set[str] = set()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def mask_email(email: str) -> str:
    """Show only the first two characters + ``***`` + domain.

    Examples:
        ``jose@airhero.com`` -> ``jo***@airhero.com``
        ``a@b.com``          -> ``a***@b.com``
    """
    local, at, domain = email.partition("@")
    show = local[:2] if len(local) > 2 else local
    return f"{show}***{at}{domain}"


def get_pending_signup_by_email(email: str) -> PendingSignup | None:
    """Look up a pending (or previously-pending) signup by admin email."""
    return _pending_signups.get(email)


def get_pending_signup_by_user_id(user_id: str) -> PendingSignup | None:
    """Look up a pending signup by the admin user's UUID."""
    for signup in _pending_signups.values():
        if signup.admin_user_id == user_id:
            return signup
    return None


def _store_signup(signup: PendingSignup) -> None:
    """Store a pending signup keyed by both email and signup ID."""
    _pending_signups[signup.admin_email] = signup
    _pending_signups[signup.signup_id] = signup


def _remove_signup(signup: PendingSignup) -> None:
    """Remove a pending signup from the in-memory store."""
    _pending_signups.pop(signup.admin_email, None)
    _pending_signups.pop(signup.signup_id, None)


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def start_signup(request: SignupStartRequest) -> SignupStartResponse:
    """Initiate the signup flow.

    1. Reject duplicate registrations (same email).
    2. Hash the provided password.
    3. Create a ``PendingSignup`` record with fresh UUIDs.
    4. Generate an email-verification JWT and store its hash.
    5. Persist to the in-memory store.
    6. Dispatch the verification email (logged to console for MVP).
    """
    # 1. Check for duplicates
    existing = get_pending_signup_by_email(str(request.admin_email))
    if existing is not None:
        raise HTTPException(
            status_code=409,
            detail="An account with this email is already being registered or active.",
        )

    # 2. Hash the password
    password_hash = hash_password(request.password)

    # 3. Create the pending-signup record (UUIDs are auto-generated by the model)
    signup = PendingSignup(
        company_name=request.company_name,
        bidder_display_name=request.bidder_display_name,
        primary_contact=request.primary_contact,
        admin_email=str(request.admin_email),
        password_hash=password_hash,
        phone=request.phone,
        location=request.location,
    )

    # 4. Generate and store the email-verification token
    token = generate_verification_token(subject=signup.admin_user_id)
    signup.email_verification_token = token

    # 5. Store in memory
    _store_signup(signup)

    # 6. Send verification email
    send_verification_email(str(request.admin_email), token)

    # 7. Return masked response
    return SignupStartResponse(
        signup_id=signup.signup_id,
        email=mask_email(str(request.admin_email)),
    )


def verify_email(token: str) -> EmailVerifyResponse:
    """Verify the email-verification token and advance signup to the 2FA-setup
    stage.

    Returns a short-lived temporary token (``type: "2fa_setup"``) that the
    client must present to the 2FA endpoints.
    """
    # 1. Decode the token
    user_id = verify_verification_token(token)
    if user_id is None:
        raise HTTPException(
            status_code=400,
            detail="Invalid or expired token",
        )

    # 2. Find the pending signup
    signup = get_pending_signup_by_user_id(user_id)
    if signup is None:
        raise HTTPException(
            status_code=400,
            detail="Invalid or expired token",
        )

    # 3. Guard: must be in the expected state
    if signup.status != UserStatus.pending_email_verification:
        raise HTTPException(
            status_code=400,
            detail="Email already verified",
        )

    # 4. Advance status
    signup.status = UserStatus.email_verified_pending_2fa
    signup.updated_at = datetime.now(tz=timezone.utc)

    # 5. Issue a short-lived token for the 2FA setup step
    temp_token = create_access_token(
        subject=signup.admin_user_id,
        extra_claims={"type": "2fa_setup"},
        expires_delta_minutes=15,
    )

    # 6. Return response
    return EmailVerifyResponse(
        email=signup.admin_email,
        temp_token=temp_token,
        status=signup.status,
    )


def start_2fa_setup(temp_token: str) -> TwoFASetupStartResponse:
    """Begin TOTP enrollment.

    Expects a valid ``2fa_setup`` JWT (issued by :func:`verify_email`).

    Generates a TOTP secret if one hasn't been created yet, builds the
    provisioning URI, and optionally returns a QR code SVG.
    """
    # 1. Decode and validate token
    try:
        payload = decode_token(temp_token)
    except HTTPException:
        raise HTTPException(
            status_code=403,
            detail="Invalid or expired token",
        )

    if payload.get("type") != "2fa_setup":
        raise HTTPException(
            status_code=403,
            detail="Invalid token type",
        )

    user_id = payload.get("sub")
    if not isinstance(user_id, str) or not user_id:
        raise HTTPException(
            status_code=403,
            detail="Invalid token",
        )
    signup = get_pending_signup_by_user_id(user_id)
    if signup is None:
        raise HTTPException(
            status_code=403,
            detail="Invalid token",
        )

    # 2. Generate TOTP secret (once)
    if signup.totp_secret is None:
        signup.totp_secret = generate_totp_secret()

    # 3. Build provisioning URI
    provisioning_uri = get_totp_provisioning_uri(
        secret=signup.totp_secret,
        email=signup.admin_email,
    )

    # 4. Generate QR code SVG
    qr_svg = get_totp_qr_svg_base64(provisioning_uri)

    # 5. Return provisioning info
    return TwoFASetupStartResponse(
        provisioning_uri=provisioning_uri,
        secret=signup.totp_secret,
        qr_svg_base64=qr_svg,
        has_recovery_codes=False,
    )


def confirm_2fa_setup(temp_token: str, totp_code: str) -> TwoFASetupConfirmResponse:
    """Complete TOTP enrollment and activate the account.

    Validates the provided TOTP code, generates recovery codes, issues
    access/refresh tokens, and promotes the signup to ``active`` status.
    """
    # 1. Decode and validate token
    try:
        payload = decode_token(temp_token)
    except HTTPException:
        raise HTTPException(
            status_code=403,
            detail="Invalid or expired token",
        )

    if payload.get("type") != "2fa_setup":
        raise HTTPException(
            status_code=403,
            detail="Invalid token type",
        )

    user_id = payload.get("sub")
    if not isinstance(user_id, str) or not user_id:
        raise HTTPException(
            status_code=403,
            detail="Invalid token",
        )
    signup = get_pending_signup_by_user_id(user_id)
    if signup is None:
        raise HTTPException(
            status_code=403,
            detail="Invalid token",
        )

    # 2. Verify the TOTP code
    if signup.totp_secret is None:
        raise HTTPException(
            status_code=400,
            detail="TOTP not initialised. Please start 2FA setup first.",
        )

    if not verify_totp_code(signup.totp_secret, totp_code):
        raise HTTPException(
            status_code=400,
            detail="Invalid TOTP code",
        )

    # 3. Mark 2FA as enabled
    signup.two_factor_enabled = True

    # 4. Generate & store recovery codes
    codes = generate_recovery_codes(count=8)
    signup.recovery_codes = codes

    # 5. Activate the account
    signup.status = UserStatus.active
    signup.org_status = OrgStatus.active
    signup.updated_at = datetime.now(tz=timezone.utc)

    # 6. Issue auth tokens
    access_token = create_access_token(subject=signup.admin_user_id)
    refresh_token = create_refresh_token(subject=signup.admin_user_id)

    # 7. Return activation response
    return TwoFASetupConfirmResponse(
        user_id=signup.admin_user_id,
        email=signup.admin_email,
        status=signup.status,
        org_status=signup.org_status,
        access_token=access_token,
        refresh_token=refresh_token,
        recovery_codes=[RecoveryCodeResponse(code=c) for c in codes],
    )


def login(email: str, password: str) -> LoginResponse:
    """Authenticate a user by email and password.

    Behaviour depends on the current signup/user status:

    * ``pending_email_verification`` -> 403
    * ``email_verified_pending_2fa``  -> returns a ``2fa_challenge`` temp token
    * ``active``                      -> returns access/refresh tokens directly
      unless two-factor authentication is enabled, in which case it returns a
      ``2fa_challenge`` temp token.
    """
    # 1. Look up the user
    signup = get_pending_signup_by_email(email)
    if signup is None:
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
        )

    # 2. Verify password
    if not verify_password(password, signup.password_hash):
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
        )

    # 3. Branch on status
    if signup.status == UserStatus.pending_email_verification:
        raise HTTPException(
            status_code=403,
            detail="Email not verified",
        )

    def build_2fa_challenge_response() -> LoginResponse:
        temp_token = create_access_token(
            subject=signup.admin_user_id,
            extra_claims={"type": "2fa_challenge"},
            expires_delta_minutes=15,
        )
        return LoginResponse(
            challenge_required=True,
            challenge_type="totp",
            temp_token=temp_token,
            email=signup.admin_email,
            status=signup.status,
        )

    if signup.status == UserStatus.email_verified_pending_2fa:
        return build_2fa_challenge_response()

    if signup.status == UserStatus.active and signup.two_factor_enabled:
        return build_2fa_challenge_response()

    if signup.status == UserStatus.active:
        access_token = create_access_token(subject=signup.admin_user_id)
        refresh_token = create_refresh_token(subject=signup.admin_user_id)
        return LoginResponse(
            challenge_required=False,
            access_token=access_token,
            refresh_token=refresh_token,
            user_id=signup.admin_user_id,
            email=signup.admin_email,
            status=signup.status,
        )

    # Any other status (locked, disabled)
    raise HTTPException(
        status_code=403,
        detail=f"Account is {signup.status.value}",
    )


def challenge_2fa(temp_token: str, code: str) -> TwoFAChallengeResponse:
    """Complete a 2FA challenge during login.

    Accepts either a TOTP code (6 chars) or a recovery code (>6 chars).
    On success, returns access and refresh tokens.

    Recovery codes are consumed (removed from the user's list) after use.
    """
    # 1. Decode and validate token
    try:
        payload = decode_token(temp_token)
    except HTTPException:
        raise HTTPException(
            status_code=403,
            detail="Invalid or expired token",
        )

    if payload.get("type") != "2fa_challenge":
        raise HTTPException(
            status_code=403,
            detail="Invalid token type",
        )

    user_id = payload.get("sub")
    if not isinstance(user_id, str) or not user_id:
        raise HTTPException(
            status_code=403,
            detail="Invalid token",
        )
    signup = get_pending_signup_by_user_id(user_id)
    if signup is None:
        raise HTTPException(
            status_code=403,
            detail="Invalid token",
        )

    # 2. Determine code type and validate
    is_recovery = len(code) > 6
    valid = False

    if is_recovery:
        # Try as recovery code
        if code in signup.recovery_codes:
            # Consume this recovery code
            signup.recovery_codes = [c for c in signup.recovery_codes if c != code]
            valid = True
    else:
        # Verify as TOTP
        if signup.totp_secret is not None and verify_totp_code(
            signup.totp_secret, code
        ):
            valid = True

    if not valid:
        raise HTTPException(
            status_code=400,
            detail="Invalid code",
        )

    # 3. Issue auth tokens
    access_token = create_access_token(subject=signup.admin_user_id)
    refresh_token = create_refresh_token(subject=signup.admin_user_id)

    return TwoFAChallengeResponse(
        access_token=access_token,
        refresh_token=refresh_token,
        user_id=signup.admin_user_id,
        email=signup.admin_email,
    )


def forgot_password(email: str) -> ForgotPasswordResponse:
    """Request a password-reset email.

    Always returns the same generic message to prevent email enumeration.
    The email is only sent if the account exists.
    """
    signup = get_pending_signup_by_email(email)
    if signup is not None:
        token = create_access_token(
            subject=signup.admin_user_id,
            extra_claims={
                "type": "password_reset",
                "email": email,
            },
            expires_delta_minutes=30,
        )
        send_password_reset_email(email, token)

    return ForgotPasswordResponse()


def reset_password(token: str, new_password: str) -> dict[str, str]:
    """Reset a user's password using a valid password-reset JWT."""
    # 1. Decode token
    try:
        payload = decode_token(token)
    except HTTPException:
        raise HTTPException(
            status_code=400,
            detail="Invalid or expired token",
        )

    if payload.get("type") != "password_reset":
        raise HTTPException(
            status_code=400,
            detail="Invalid token type",
        )

    user_id = payload.get("sub")
    if not isinstance(user_id, str) or not user_id:
        raise HTTPException(
            status_code=400,
            detail="Invalid token",
        )
    signup = get_pending_signup_by_user_id(user_id)
    if signup is None:
        raise HTTPException(
            status_code=400,
            detail="Invalid token",
        )

    # 2. Hash and store the new password
    signup.password_hash = hash_password(new_password)
    signup.updated_at = datetime.now(tz=timezone.utc)

    return {"message": "Password updated successfully."}


def refresh_access_token(refresh_token_str: str) -> dict[str, str]:
    """Issue a new access/refresh token pair from a valid refresh token."""
    # 1. Decode the refresh token
    try:
        payload = decode_token(refresh_token_str)
    except HTTPException:
        raise HTTPException(
            status_code=401,
            detail="Invalid refresh token",
        )

    if payload.get("type") != "refresh":
        raise HTTPException(
            status_code=401,
            detail="Invalid token type",
        )

    user_id = payload.get("sub")
    if not isinstance(user_id, str) or not user_id:
        raise HTTPException(
            status_code=401,
            detail="Invalid refresh token",
        )

    # 2. Issue fresh tokens
    new_access_token = create_access_token(subject=user_id)
    new_refresh_token = create_refresh_token(subject=user_id)

    return {
        "access_token": new_access_token,
        "refresh_token": new_refresh_token,
    }
